### ISSUE TITLE
Visual error

### ISSUE THREAD

**Issue by LordNutBuster** [FlamingTaco113/MinecraftPlus-Datapack#1]
Hi. I really like the concept of your data pack and am enjoying the enchantments and structures. however im having some visual issues and im not sure how to fix. the animals are either invisible, a small head, a small floating pickaxe, or a large floating pickaxe. im not sure how to fix this. do i need a resource pack or something? any info will help. thank you

**Comment by FlamingTaco113** [comment]
There is a resource pack which you download alongside the datapack

**Comment by LordNutBuster** [comment]
Where? i couldnt find it anywhere
